name: CI

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Run-Common-CI:
    uses: dm-vdo/vdo-org-actions/.github/workflows/ci.yaml@main
    with:
      # Turn this off temporarily
      run-public-tests: true
      public-tests-action: make jenkins
      public-tests-action-failure: |
          cd logs
          for i in *;
          do
            if [ -d "$i" ]; then
              cd $i
              for file in *::*.log;
              do
                [ -e "$file" ] || continue
                mv "${file}" "${file/::/--}"
              done
              cd ..
            else
              mv "${i}" "${i/::/--}"
            fi
          done

      # Call the Jenkins job
      run-private-tests: true
      private-tests-action: /permabit/ops/scripts/runJenkinsJob common-github
      private-tests-action-failure: echo "Private testing failed"
